In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
try:
    %tensorflow_version 1.x
except Exception:
    pass

import tensorflow as tf
tf.__version__

'1.15.2'

In [ ]:
import tensorflow as tf

hello = tf.constant('Hello World!')

sess = tf.Session()
print(sess.run(hello))
sess.close()

b'Hello World!'


In [ ]:
a = 10
b = 10
print(tf.add(a, b))

sess = tf.Session()
print(sess.run(tf.add(a, b)))
sess.close()

Tensor("Add:0", shape=(), dtype=int32)
20


In [ ]:
%tensorflow_version 2.x

TensorFlow is already loaded. Please restart the runtime to change versions.


<h2>메뉴, 런타임 | 런타임 다시시작<br></h2>
단축키 : ctrl+M

In [ ]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [ ]:
a = tf.constant(5)
a

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
a.shape

TensorShape([])

In [ ]:
a.dtype

tf.int32

In [ ]:
a.numpy()

5

In [ ]:
b = tf.constant(3)
b

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
b.shape

TensorShape([])

In [ ]:
b.dtype

tf.int32

In [ ]:
b.numpy()

3

In [ ]:
a = tf.constant(5)
b = tf.constant(3)
print(a+b)

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
c = tf.constant('Hello World!')
print(c)
print(c.numpy())

tf.Tensor(b'Hello World!', shape=(), dtype=string)
b'Hello World!'


<h2>Tensor</h2>

In [ ]:
a = tf.constant([1, 2, 3])
a.shape

TensorShape([3])

In [ ]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])
a.shape

TensorShape([2, 3])

In [ ]:
a = tf.constant([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
a.shape

TensorShape([2, 2, 3])

In [ ]:
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

<h2>tf.cond</h2>

In [ ]:
x = tf.constant(1.)
bool = tf.constant(True)
res = tf.cond(bool, lambda: tf.add(x, 1. ), lambda: tf.add(x, 10. ))

print(res)
print(res.numpy())

tf.Tensor(2.0, shape=(), dtype=float32)
2.0


In [ ]:
x = tf.constant (2)
y = tf.constant (5)
def f1(): return tf.multiply(x, 17)
def f2(): return tf.add(y, 23)
r = tf.cond(tf.less(x, y), f1, f2)
r.numpy ()

34

In [ ]:
t = tf.constant([1, 2, 3])
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([5, 6, 7])
print((x+y) .numpy())

[ 6  8 10]


In [ ]:
a = tf.constant([5], dtype=tf.float32)
b = tf.constant([10], dtype=tf.float32)
c = tf.constant([2], dtype=tf.float32)
print (a. numpy())

d = a * b + c

print(d)
print(d.numpy())

[5.]
tf.Tensor([52.], shape=(1,), dtype=float32)
[52.]


In [ ]:
x = tf.constant([[0], [10], [20], [30]])
y = tf.constant([0, 1, 2])

print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
import numpy as np
print(np.arange(3))
print(np.ones((3, 3)))
print()

x = tf.constant ((np.arange(3)))
y = tf.constant([5], dtype=tf. int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [ ]:
x = tf.constant ((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print((x+y).numpy())

x = tf.constant((np.ones((3, 3))))
y = tf.constant(np.arange(3), dtype=tf.double)
print((x+y).numpy())

x = tf.constant (np.arange(3).reshape(3, 1))
y = tf.constant(np.arange(3))
print((x+y).numpy())

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a = 2
b = 3
c = tf.add(a, b)
print(c.numpy())

5


In [ ]:
x = 2
y = 3
add_op = tf.add(x, y)
mul_op = tf.multiply(x, y)
pow_op = tf.pow(add_op, mul_op)

print(pow_op.numpy ())

15625


In [ ]:
a = tf.constant(2.)
b = tf.constant(3.)
c = tf.constant(5.)

mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

print("mean =", mean.numpy())
print("sum =", sum.numpy())

mean = 3.3333333
sum = 10.0


In [ ]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[2., 0.], [1., 2.]])

gop = tf.matmul(matrix1, matrix2)
print(gop.numpy())

gop = tf.matmul(matrix2, matrix1)
print(gop. numpy())

[[ 4.  4.]
 [10.  8.]]
[[ 2.  4.]
 [ 7. 10.]]
